#!/bin/bash

###############################################################################
# SmartHavenAI.com VPS Deployment Script
# This script sets up and deploys the Transcript Parser application
# Target: Hostinger VPS (72.62.86.210)
# Author: Generated by Claude Code
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
VPS_IP="72.62.86.210"
DOMAIN="smarthavenai.com"
N8N_DOMAIN="n8n.smarthavenai.com"
APP_DIR="/var/www/smarthaven"
REPO_URL="https://github.com/KevenWMarkham/transcript-parser.git"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   SmartHavenAI.com Deployment Script                      ║${NC}"
echo -e "${BLUE}║   Transcript Parser + N8N + PostgreSQL + Nginx            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to print section headers
print_section() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Function to print success messages
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Function to print error messages
print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Function to print warnings
print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root or with sudo"
    exit 1
fi

print_section "Phase 1: System Update & Docker Installation"

echo "Updating system packages..."
apt update && apt upgrade -y
print_success "System updated"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    print_success "Docker installed"
else
    print_success "Docker already installed: $(docker --version)"
fi

# Install Docker Compose plugin
if ! docker compose version &> /dev/null; then
    echo "Installing Docker Compose plugin..."
    apt install -y docker-compose-plugin
    print_success "Docker Compose installed"
else
    print_success "Docker Compose already installed: $(docker compose version)"
fi

# Enable and start Docker
systemctl enable docker
systemctl start docker
print_success "Docker service enabled and started"

print_section "Phase 2: Application Directory Setup"

# Create application directory
mkdir -p "$APP_DIR"
cd "$APP_DIR"
print_success "Application directory created: $APP_DIR"

print_section "Phase 3: Repository Clone/Update"

if [ -d ".git" ]; then
    print_warning "Repository already exists. Pulling latest changes..."
    git pull origin master
    print_success "Repository updated"
else
    echo "Cloning repository..."
    git clone "$REPO_URL" .
    print_success "Repository cloned"
fi

print_section "Phase 4: Environment Configuration"

if [ ! -f ".env.production" ]; then
    print_warning "Creating .env.production from template..."
    cp .env.production.example .env.production

    echo ""
    echo -e "${YELLOW}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}║  IMPORTANT: Configure Environment Variables               ║${NC}"
    echo -e "${YELLOW}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Please edit .env.production and set the following:"
    echo "  1. POSTGRES_PASSWORD (strong password)"
    echo "  2. N8N_PASSWORD (strong password)"
    echo "  3. VITE_GEMINI_API_KEY (your Gemini API key)"
    echo ""
    read -p "Press Enter when you've updated .env.production..."

    # Open editor
    nano .env.production
    print_success ".env.production configured"
else
    print_success ".env.production already exists"
fi

# Create SSL certificate directories
mkdir -p certbot/conf certbot/www
print_success "SSL certificate directories created"

print_section "Phase 5: DNS Verification"

echo "Checking DNS resolution..."
DNS_CHECK=0

for DOMAIN_CHECK in "$DOMAIN" "www.$DOMAIN" "$N8N_DOMAIN"; do
    IP=$(nslookup "$DOMAIN_CHECK" | grep "Address:" | tail -1 | awk '{print $2}')
    if [ "$IP" == "$VPS_IP" ]; then
        print_success "$DOMAIN_CHECK resolves to $VPS_IP"
        ((DNS_CHECK++))
    else
        print_error "$DOMAIN_CHECK does not resolve to $VPS_IP (got: $IP)"
    fi
done

if [ $DNS_CHECK -lt 3 ]; then
    print_warning "DNS not fully configured. Please update DNS records:"
    echo "  A record: @ → $VPS_IP"
    echo "  A record: www → $VPS_IP"
    echo "  A record: n8n → $VPS_IP"
    echo ""
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_section "Phase 6: SSL Certificate Setup"

# Start Nginx temporarily for Let's Encrypt validation
echo "Starting Nginx for SSL validation..."
docker compose up nginx -d
sleep 5

# Get email for Let's Encrypt
read -p "Enter your email for Let's Encrypt notifications: " LE_EMAIL

# Obtain SSL certificate for main domain
echo "Obtaining SSL certificate for $DOMAIN..."
docker compose run --rm certbot certonly --webroot \
  --webroot-path=/var/www/certbot \
  --email "$LE_EMAIL" \
  --agree-tos \
  --no-eff-email \
  -d "$DOMAIN" \
  -d "www.$DOMAIN" || print_warning "SSL certificate for $DOMAIN may have failed"

# Obtain SSL certificate for N8N subdomain
echo "Obtaining SSL certificate for $N8N_DOMAIN..."
docker compose run --rm certbot certonly --webroot \
  --webroot-path=/var/www/certbot \
  --email "$LE_EMAIL" \
  --agree-tos \
  --no-eff-email \
  -d "$N8N_DOMAIN" || print_warning "SSL certificate for $N8N_DOMAIN may have failed"

# Stop temporary Nginx
docker compose down
print_success "SSL certificates obtained"

print_section "Phase 7: Deploy Full Stack"

echo "Building and starting all services..."
docker compose up -d --build

echo "Waiting for services to start..."
sleep 15

# Check container status
echo ""
echo "Container Status:"
docker compose ps

print_success "All services deployed"

print_section "Phase 8: Firewall Configuration"

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
    echo "Installing UFW..."
    apt install -y ufw
fi

# Configure firewall
echo "Configuring firewall..."
ufw --force allow 22/tcp
ufw --force allow 80/tcp
ufw --force allow 443/tcp
ufw --force enable

print_success "Firewall configured"
ufw status verbose

print_section "Phase 9: Deployment Verification"

echo "Testing HTTP..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://$DOMAIN" || echo "000")
if [ "$HTTP_CODE" == "301" ] || [ "$HTTP_CODE" == "200" ]; then
    print_success "HTTP responding (code: $HTTP_CODE)"
else
    print_warning "HTTP test returned: $HTTP_CODE"
fi

echo "Testing HTTPS..."
HTTPS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN" || echo "000")
if [ "$HTTPS_CODE" == "200" ]; then
    print_success "HTTPS responding (code: $HTTPS_CODE)"
else
    print_warning "HTTPS test returned: $HTTPS_CODE"
fi

echo "Testing N8N..."
N8N_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://$N8N_DOMAIN" || echo "000")
if [ "$N8N_CODE" == "200" ] || [ "$N8N_CODE" == "401" ]; then
    print_success "N8N responding (code: $N8N_CODE)"
else
    print_warning "N8N test returned: $N8N_CODE"
fi

print_section "Deployment Complete!"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Deployment Successful!                                    ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Application URLs:"
echo -e "  ${BLUE}Main App:${NC}  https://$DOMAIN"
echo -e "  ${BLUE}N8N:${NC}       https://$N8N_DOMAIN"
echo ""
echo "Next steps:"
echo "  1. Visit https://$DOMAIN to verify the app is running"
echo "  2. Log into https://$N8N_DOMAIN with your N8N credentials"
echo "  3. Check container logs: docker compose logs -f"
echo "  4. Monitor container health: docker compose ps"
echo ""
echo "Useful commands:"
echo "  View logs:       docker compose logs -f app"
echo "  Restart app:     docker compose restart app"
echo "  Update app:      git pull && docker compose up -d --build app"
echo "  Database backup: docker compose exec postgres pg_dump -U postgres transcript_parser > backup.sql"
echo ""
echo -e "${GREEN}🚀 Deployment complete!${NC}"
echo ""
